export const mensTops = [
  {
    name: "t-shirt",
    imageSrc: "https://m.media-amazon.com/images/I/719zjpQzotL._AC_SX679_.jpg",
    linkSrc:
      "https://www.amazon.ca/Boyzn-Workout-Moisture-T-Shirts-Athletic/dp/B0BCFS862T/",
    moods: ["casual", "energetic", "playful"],
    conditions: [
      [
        "sunny",
        "clear",
        "partly cloudy",
        "light rain",
        "patchy light rain",
        "moderate rain shower",
        "overcast",
        "cloudy",
        "light drizzle",
      ],
    ],
    temperatures: ["hot", "mild"],
  },
  {
    name: "tank-top",
    imageSrc: "https://m.media-amazon.com/images/I/71nVw2HK-WL._AC_SX569_.jpg",
    linkSrc:
      "https://www.amazon.ca/Amazon-Essentials-Slim-Fit-Solid-X-Small/dp/B07HJBHZ7T/",
    moods: ["casual", "energetic", "playful"],
    conditions: [
      [
        "sunny",
        "clear",
        "partly cloudy",
        "light rain",
        "patchy light rain",
        "overcast",
        "cloudy",
      ],
    ],
    temperatures: ["hot", "mild"],
  },
  {
    name: "long-sleeve shirt",
    imageSrc: "https://m.media-amazon.com/images/I/71lo4dTetjL._AC_SX569_.jpg",
    linkSrc:
      "https://www.amazon.ca/MAGCOMSEN-Protection-Outdoor-Running-Fishing/dp/B097YGJ65H/",
    moods: ["confident", "elegant", "formal", "casual", "energetic"],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light rain",
      "light drizzle",
      "patchy snow possible",
      "patchy light snow",
      "patchy moderate snow",
      "light snow",
      "patch heavy snow",
      "moderate snow",
      "heavy snow",
      "light rain shower",
      "moderate or heavy rain shower",
      "patchy light snow with thunder",
      "patchy light rain with thunder",
      "moderate rain",
      "heavy rain",
    ],
    temperatures: ["mild", "cool", "cold"],
  },
  {
    name: "thermal-shirt",
    imageSrc: "https://m.media-amazon.com/images/I/41l1fumERoL._AC_SX679_.jpg",
    linkSrc:
      "https://www.amazon.ca/SIMIYA-Thermal-Underwear-Fleece-Sleeve/dp/B0DBLFJBHC/",
    moods: [
      "casual",
      "confident",
      "energetic",
      "rebellious",
      "mysterious",
      "playful",
    ],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light drizzle",
      "patchy snow possible",
      "patchy light snow",
      "moderate snow",
      "heavy snow",
      "patchy heavy snow",
      "light snow",
      "patchy freezing drizzle",
      "light freezing drizzle",
      "freezing fog",
      "light rain",
      "light freezing rain",
      "moderate rain",
      "heavy rain",
      "patchy light snow with thunder",
      "patchy light rain with thunder",
      "blowing snow",
      "blizzard",
      "moderate freezing rain",
      "heavy freezing rain",
      "light sleet",
      "moderate sleet",
    ],
    temperatures: ["mild", "cool", "cold"],
  },
  {
    name: "blouse",
    imageSrc: "https://m.media-amazon.com/images/I/61SCdheDg9L._AC_SX569_.jpg",
    linkSrc:
      "https://www.amazon.ca/NANAMEEI-Cotton-Shirts-Casual-Lightweight/dp/B0B1ZLFLTG/",
    moods: [
      "elegant",
      "confident",
      "formal",
      "casual",
      "playful",
      "mysterious",
      "rebellious",
    ],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light drizzle",
      "moderate rain at times",
      "patchy light snow",
      "light snow",
      "patchy moderate snow",
      "moderate snow",
      "patchy heavy snow",
      "light snow showers",
      "patchy light rain with thunder",
      "patchy light snow with thunder",
      "light rain shower",
      "moderate rain shower",
      "heavy rain shower",
      "light drizzle",
      "light freezing rain",
      "light sleet",
      "patchy freezing drizzle",
    ],
    temperatures: ["cool", "mild", "cold"],
  },
  {
    name: "hoodie",
    imageSrc: "https://m.media-amazon.com/images/I/61SCdheDg9L._AC_SX569_.jpg",
    linkSrc:
      "https://www.amazon.ca/JMIERR-Hoodies-Sweatshirt-Drawstring-Athletic/dp/B0CG4JFMKK",
    moods: [
      "casual",
      "confident",
      "energetic",
      "rebellious",
      "playful",
      "mysterious",
    ],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light rain",
      "patchy snow possible",
      "light snow",
      "patchy moderate snow",
      "moderate snow",
      "patchy heavy snow",
      "heavy snow",
      "light snow showers",
      "light freezing rain",
      "light rain shower",
      "moderate or heavy rain shower",
      "patchy light snow with thunder",
      "blowing snow",
      "blizzard",
      "moderate sleet",
      "moderate freezing rain",
      "heavy freezing rain",
    ],
    temperatures: ["mild", "cool", "cold"],
  },
];

export const womensTops = [
  {
    name: "t-shirt",
    imageSrc: "https://m.media-amazon.com/images/I/81ys3yKhU0L._AC_SX679_.jpg",
    linkSrc:
      "https://www.amazon.ca/Hanes-Essentials-Crewneck-Athletic-XX-Large/dp/B0CHN6J16L",
    moods: ["casual", "energetic", "playful"],
    conditions: [
      [
        "sunny",
        "clear",
        "partly cloudy",
        "light rain",
        "patchy light rain",
        "moderate rain shower",
        "overcast",
        "cloudy",
        "light drizzle",
      ],
    ],
    temperatures: ["hot", "mild"],
  },
  {
    name: "crop-top",
    imageSrc: "https://m.media-amazon.com/images/I/71zMSHlFtYL._AC_SX679_.jpg",
    linkSrc:
      "https://www.amazon.ca/RIROW-Summer-Ribbed-Ahletic-Ladies/dp/B0CN9CX7JC/",
    moods: ["casual", "energetic", "playful"],
    conditions: [
      [
        "sunny",
        "clear",
        "partly cloudy",
        "light rain",
        "patchy light rain",
        "overcast",
        "cloudy",
      ],
    ],
    temperatures: ["hot", "mild"],
  },
  {
    name: "long-sleeve shirt",
    imageSrc: "https://m.media-amazon.com/images/I/81ZsGUkfDtL._AC_SX679_.jpg",
    linkSrc:
      "https://www.amazon.ca/Pylnily-Long-Sleeve-Shirts-Workout/dp/B0D9XZ2J7M/",
    moods: ["confident", "elegant", "formal", "casual", "energetic"],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light rain",
      "light drizzle",
      "patchy snow possible",
      "patchy light snow",
      "patchy moderate snow",
      "light snow",
      "patch heavy snow",
      "moderate snow",
      "heavy snow",
      "light rain shower",
      "moderate or heavy rain shower",
      "patchy light snow with thunder",
      "patchy light rain with thunder",
      "moderate rain",
      "heavy rain",
    ],
    temperatures: ["mild", "cool", "cold"],
  },
  {
    name: "thermal-shirt",
    imageSrc: "https://m.media-amazon.com/images/I/81nj8K2RqCL._AC_SX569_.jpg",
    linkSrc:
      "https://www.amazon.ca/QOMEWA-Thermal-Stretch-Lightweight-Undershirt/dp/B0DBFYLKK3",
    moods: [
      "casual",
      "confident",
      "energetic",
      "rebellious",
      "mysterious",
      "playful",
    ],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light drizzle",
      "patchy snow possible",
      "patchy light snow",
      "moderate snow",
      "heavy snow",
      "patchy heavy snow",
      "light snow",
      "patchy freezing drizzle",
      "light freezing drizzle",
      "freezing fog",
      "light rain",
      "light freezing rain",
      "moderate rain",
      "heavy rain",
      "patchy light snow with thunder",
      "patchy light rain with thunder",
      "blowing snow",
      "blizzard",
      "moderate freezing rain",
      "heavy freezing rain",
      "light sleet",
      "moderate sleet",
    ],
    temperatures: ["mild", "cool", "cold"],
  },
  {
    name: "blouse",
    imageSrc: "https://m.media-amazon.com/images/I/71nAlbNAkKL._AC_SX569_.jpg",
    linkSrc:
      "https://www.amazon.ca/SPRING-SEAON-Collared-Blouses-Chiffon/dp/B0BCWCKF8D/",
    moods: [
      "elegant",
      "confident",
      "formal",
      "casual",
      "playful",
      "mysterious",
      "rebellious",
    ],
    conditions: [
      "sunny",
      "clear",
      "partly cloudy",
      "cloudy",
      "overcast",
      "mist",
      "patchy rain possible",
      "light drizzle",
      "moderate rain at times",
      "patchy light snow",
      "light snow",
      "patchy moderate snow",
      "moderate snow",
      "patchy heavy snow",
      "light snow showers",
      "patchy light rain with thunder",
      "patchy light snow with thunder",
      "light rain shower",
      "moderate rain shower",
      "heavy rain shower",
      "light drizzle",
      "light freezing rain",
      "light sleet",
      "patchy freezing drizzle",
    ],
    temperatures: ["cool", "mild", "cold"],
  },
  {
    name: "hoodie",
    imageSrc: "https://m.media-amazon.com/images/I/71ggU4lJAsL._AC_SY741_.jpg",
    linkSrc:
      "https://www.amazon.ca/Jhsnjnr-Hoodies-Oversized-Pullover-Sweatshirt/dp/B0CGHY1XM1",
    moods: [
      "casual",
      "confident",
      "energetic",
      "rebellious",
      "playful",
      "mysterious",
    ],
    conditions: ["sunny", "clear", "partly cloudy"],
    temperatures: ["mild", "cool", "cold"],
  },
];
